server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
    - type: console
      timeZone: IST

logging:
  level: INFO
  loggers:
    deprecation: ERROR
    org.hibernate: ERROR
    QueuedSender: WARN
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

shards:
  shards:
    - driverClass: org.mariadb.jdbc.Driver
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      url: ${SHARD1_CONNECTION_STRING}
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
        #hibernate.hbm2ddl.auto: create
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      logAbandonedConnections: true
      logValidationErrors: true
      checkConnectionWhileIdle: true
      checkConnectionOnConnect: true
      validationQueryTimeout: 1s
      removeAbandoned: true
      evictionInterval: 30s
      minIdleTime: 1m
    - driverClass: org.mariadb.jdbc.Driver
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      url: ${SHARD1_CONNECTION_STRING}
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
        #hibernate.hbm2ddl.auto: create
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      logAbandonedConnections: true
      logValidationErrors: true
      checkConnectionWhileIdle: true
      checkConnectionOnConnect: true
      validationQueryTimeout: 1s
      removeAbandoned: true
      evictionInterval: 30s
      minIdleTime: 1m

riemann:
  host: ${RIEMANN_HOST}
  port: 5555
  prefix: covid.${CONFIG_ENV}.statesman
  pollingInterval: 30
  tags:
    - statesman

swagger:
  resourcePackage: io.appform.statesman.server.resources
  title: Statesman
  description: Statesman Backend

eventPublisherConfig:
  connections: 10
  idleTimeOutSeconds: 30
  connectTimeoutMs: 10000
  opTimeoutMs: 10000
  endpoint: "http://localhost:8080/sendMsg"
  eventTopics:
    REPORTING: reporting
    APP: app

callbackTransformationTemplates:
  templates:
    punjab_ozonetel:
      type: ONE_SHOT
      template: >-
        {
          "callerPhone" : \"{{number}}\",
          "language": {{{ map_lookup op_1='EN' op_2='KA' op_3='HI' pointer='/payload[question1]/0'}}},
          "covidTest": {{{ map_lookup op_1=true op_2=false pointer='/payload[question2]/0'}}},
          "ageGreaterThanSixty": "{{ map_lookup op_1=true op_2=false pointer='/payload[question3]/0'}}},
          "travelled": {{{ map_lookup op_1=true op_2=false pointer='/payload[question4]/0'}}},
          "contact": {{{ map_lookup op_1=true op_2=false pointer='/payload[question5]/0'}}},
          "existingDiseases": {{{ map_lookup op_1='heart' op_2='diabetes' op_3='none' pointer='/payload[question5]/0'}}},
          "symptoms": {{{ map_lookup op_1='vomit' op_2='fever' op_3='wheezing' op_4='headache' op_5='none' pointer='/payload[question6]'}}},
        }
    mh_exotel:
      type: STEP_BY_STEP
      idPath: "/CallSid"
      templates:
        - selectionRule: "\"$.Question\" == \"1\""
          template: >-
            {
              "callerPhone" : \"{{From}}\",
              "language": {{{ map_lookup op_1='EN' op_2='KA' op_3='HI' pointer='/digits'}}}
            }
        - selectionRule: "\"$.Question\" == \"2\""
          template: >-
            {
              "covidTest": {{{ map_lookup op_1=true op_2=false pointer='/digits'}}}
            }
        - selectionRule: "\"$.Question\" == \"3\""
          template: >-
            {
              "ageGreaterThanSixty": "{{ map_lookup op_1=true op_2=false pointer='/digits'}}}
            }
        - selectionRule: "\"$.Question\" == \"4\""
          template: >-
            {
              "travelled": {{{ map_lookup op_1=true op_2=false pointer='/digits'}}}
            }
        - selectionRule: "\"$.Question\" == \"5\""
          template: >-
            {
              "contact": {{{ map_lookup op_1=true op_2=false pointer='/digits'}}}
            }
        - selectionRule: "\"$.Question\" == \"6\""
          template: >-
            {
              "existingDiseases": {{{ map_lookup op_1='heart' op_2='diabetes' op_3='none' pointer='/digits'}}}
            }
        - selectionRule: "\"$.Question\" == \"7\""
          template: >-
            {
              "symptoms": {{{ map_lookup op_1='vomit' op_2='fever' op_3='wheezing' op_4='headache' op_5='none' pointer='/digits'}}}
            }

