version: '2'
services:
   mariadb_1:
    image: mariadb:10.0.38
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: statesman_db_1
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
   mariadb_2:
    image: mariadb:10.0.38
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: statesman_db_2
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
   statesman-server:
    container_name: statesman-server
    build: .
    ports:
    - "8080:8080"
    - "8081:8081"
    # - "8084:8084"
    volumes:
    - /var/log/statesman-server
    environment:
      SHARD0_CONNECTION_STRING: jdbc:mariadb://mariadb_1/statesman_db_1?createDatabaseIfNotExist=true
      SHARD1_CONNECTION_STRING: jdbc:mariadb://mariadb_2/statesman_db_2?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: password
      FOXTROT_ENDPOINT: https://localhost:17000
      FOXTROT_TOKEN: INV_TOKEN_
      # JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8084
    depends_on:
      - mariadb_1
      - mariadb_2
