on:
    push:
        # Sequence of patterns matched against refs/heads
        branches-ignore:
            - 'master'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checking out code base
              uses: actions/checkout@v2

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Running the tests
              run: mvn test
              continue-on-error: false
